# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp
NULL

#' hello
#'
#' Prints "Hello, World!"
#'
#' @return None
#'
#' @examples
#' \dontrun{
#' hello()
#' }
#' @export
hello <- function() {
    invisible(.Call('_RcppPkgDemo_hello', PACKAGE = 'RcppPkgDemo'))
}

#' hello2
#'
#' Creates a list where keys are "foo" and "bar", and values are 0 and 1
#'
#' @return List("foo" = 0.0, "bar" = 1.0)
#'
#' @examples
#' \dontrun{
#' hello2()
#' }
#' @export
hello2 <- function() {
    .Call('_RcppPkgDemo_hello2', PACKAGE = 'RcppPkgDemo')
}

#' sumC
#' Sum NumericVector elements using C++
#'
#' @param x NumericVector to sum
#'
#' @return The sum of all elements of x as a double
#'
#' @examples
#' \dontrun{
#' x <- runif(1e3)
#' print(sumC(x))
#' }
#' @export
sumC <- function(x) {
    .Call('_RcppPkgDemo_sumC', PACKAGE = 'RcppPkgDemo', x)
}

#' sumI
#'
#' Sum NumericVector elements using C++ with an iterator
#'
#' @param x NumericVector to sum
#'
#' @return The sum of all elements of x as a double
#'
#' @examples
#' \dontrun{
#' x <- runif(1e3)
#' print(sumI(x))
#' }
#' @export
sumI <- function(x) {
    .Call('_RcppPkgDemo_sumI', PACKAGE = 'RcppPkgDemo', x)
}

